# Generated by Django 4.2.4 on 2023-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_name", models.CharField(max_length=50)),
                ("head_of_club", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("course_code", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=50)),
                ("staff", models.CharField(max_length=250)),
                ("head_of_department", models.CharField(max_length=250)),
                ("courses_in_department", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("second_name", models.CharField(max_length=250)),
                ("gender", models.CharField(max_length=250)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("male", "MALE"),
                            ("female", "FEMALE"),
                            ("don't mention", "DON'T MENTION"),
                        ],
                        max_length=250,
                    ),
                ),
                ("email", models.CharField(max_length=250)),
                ("department", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("second_name", models.CharField(max_length=250)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "MALE"),
                            ("female", "FEMALE"),
                            ("don't mention", "DON'T MENTION"),
                        ],
                        max_length=250,
                    ),
                ),
            ],
        ),
    ]
